	SUBROUTINE VOIDRI(EZERO,COORDS,NOEL)
C
      INCLUDE 'ABA_PARAM.INC'
C
      DIMENSION COORDS(3)
C
	E1=3.27726 
      Y=COORDS(3)
	VSTRESS=10.+18.0*Y
	HSTRESS=0.8*VSTRESS
	P=(VSTRESS+2.*HSTRESS)/3.0
	Q=VSTRESS-HSTRESS
	FL=0.25
	FK=0.05
	FM=1.0
	EZERO=E1-FL*LOG(Q*Q/FM/FM/P+P)+FK*LOG(Q*Q/FM/FM/P/P+1.0)
	RETURN
      END

